package br.com.facdombosco.progc.dvo.compras;
// Generated 30/06/2012 11:42:13 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="Fornecedor"
    ,catalog="progc1"
    , uniqueConstraints = @UniqueConstraint(columnNames="cnpj") 
)
public class Fornecedor  implements java.io.Serializable {


     private int idFornecedor;
     private String nome;
     private int cnpj;
     private String telefone;
     private String cidade;
     private String email;

    public Fornecedor() {
    }

	
    public Fornecedor(int idFornecedor, int cnpj, String telefone, String cidade, String email) {
        this.idFornecedor = idFornecedor;
        this.cnpj = cnpj;
        this.telefone = telefone;
        this.cidade = cidade;
        this.email = email;
    }
    public Fornecedor(int idFornecedor, String nome, int cnpj, String telefone, String cidade, String email) {
       this.idFornecedor = idFornecedor;
       this.nome = nome;
       this.cnpj = cnpj;
       this.telefone = telefone;
       this.cidade = cidade;
       this.email = email;
    }
   
     @Id 
    
    @Column(name="idFornecedor", unique=true, nullable=false)
    public int getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(int idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    
    @Column(name="nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="cnpj", unique=true, nullable=false)
    public int getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(int cnpj) {
        this.cnpj = cnpj;
    }
    
    @Column(name="telefone", nullable=false, length=11)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    
    @Column(name="cidade", nullable=false, length=200)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


