package br.com.facdombosco.progc.dvo.compras;
// Generated 07/07/2012 11:47:36 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Requisicao generated by hbm2java
 */
@Entity
@Table(name="Requisicao"
    ,catalog="progc1"
)
public class Requisicao  implements java.io.Serializable {


     private Integer idRequisicao;
     private Date dataHora;

    public Requisicao() {
    }

    public Requisicao(Date dataHora) {
       this.dataHora = dataHora;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idRequisicao", unique=true, nullable=false)
    public Integer getIdRequisicao() {
        return this.idRequisicao;
    }
    
    public void setIdRequisicao(Integer idRequisicao) {
        this.idRequisicao = idRequisicao;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataHora", nullable=false, length=19)
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }




}


