package br.com.facdombosco.progc.dvo.compras;
// Generated 07/07/2012 11:47:36 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RequisicaoProduto generated by hbm2java
 */
@Entity
@Table(name="RequisicaoProduto"
    ,catalog="progc1"
)
public class RequisicaoProduto  implements java.io.Serializable {


     private Integer idRequisicaoProduto;
     private int idRequisicao;
     private int idProduto;
     private int quantidade;

    public RequisicaoProduto() {
    }

    public RequisicaoProduto(int idRequisicao, int idProduto, int quantidade) {
       this.idRequisicao = idRequisicao;
       this.idProduto = idProduto;
       this.quantidade = quantidade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idRequisicaoProduto", unique=true, nullable=false)
    public Integer getIdRequisicaoProduto() {
        return this.idRequisicaoProduto;
    }
    
    public void setIdRequisicaoProduto(Integer idRequisicaoProduto) {
        this.idRequisicaoProduto = idRequisicaoProduto;
    }
    
    @Column(name="idRequisicao", nullable=false)
    public int getIdRequisicao() {
        return this.idRequisicao;
    }
    
    public void setIdRequisicao(int idRequisicao) {
        this.idRequisicao = idRequisicao;
    }
    
    @Column(name="idProduto", nullable=false)
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    
    @Column(name="quantidade", nullable=false)
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }




}


