package br.com.facdombosco.progc.dvo.acessos;
// Generated 23/06/2012 10:16:15 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="Usuario"
    ,catalog="progc1"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nome;
     private String nomeUsuario;
     private String senha;
     private String servicos;
     private String suprimentos;
     private String vendas;

    public Usuario() {
    }

    public Usuario(String nome, String nomeUsuario, String senha, String servicos, String suprimentos, String vendas) {
       this.nome = nome;
       this.nomeUsuario = nomeUsuario;
       this.senha = senha;
       this.servicos = servicos;
       this.suprimentos = suprimentos;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idUsuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    @Column(name="nome", length=60)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="nomeUsuario", length=10)
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }
    
    @Column(name="senha", length=10)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    @Column(name="servicos", length=1)
    public String getServicos() {
        return this.servicos;
    }
    
    public void setServicos(String servicos) {
        this.servicos = servicos;
    }
    
    @Column(name="suprimentos", length=1)
    public String getSuprimentos() {
        return this.suprimentos;
    }
    
    public void setSuprimentos(String suprimentos) {
        this.suprimentos = suprimentos;
    }
    
    @Column(name="vendas", length=1)
    public String getVendas() {
        return this.vendas;
    }
    
    public void setVendas(String vendas) {
        this.vendas = vendas;
    }




}


