package br.com.facdombosco.progc.dvo.compras;
// Generated 30/06/2012 11:42:13 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FormaPagamento generated by hbm2java
 */
@Entity
@Table(name="FormaPagamento"
    ,catalog="progc1"
)
public class FormaPagamento  implements java.io.Serializable {


     private int idFormaPagamento;
     private String nome;
     private int quantidadeDiasParcela;
     private int quantidadeParcelas;

    public FormaPagamento() {
    }

    public FormaPagamento(int idFormaPagamento, String nome, int quantidadeDiasParcela, int quantidadeParcelas) {
       this.idFormaPagamento = idFormaPagamento;
       this.nome = nome;
       this.quantidadeDiasParcela = quantidadeDiasParcela;
       this.quantidadeParcelas = quantidadeParcelas;
    }
   
     @Id 
    
    @Column(name="idFormaPagamento", unique=true, nullable=false)
    public int getIdFormaPagamento() {
        return this.idFormaPagamento;
    }
    
    public void setIdFormaPagamento(int idFormaPagamento) {
        this.idFormaPagamento = idFormaPagamento;
    }
    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="quantidadeDiasParcela", nullable=false)
    public int getQuantidadeDiasParcela() {
        return this.quantidadeDiasParcela;
    }
    
    public void setQuantidadeDiasParcela(int quantidadeDiasParcela) {
        this.quantidadeDiasParcela = quantidadeDiasParcela;
    }
    
    @Column(name="quantidadeParcelas", nullable=false)
    public int getQuantidadeParcelas() {
        return this.quantidadeParcelas;
    }
    
    public void setQuantidadeParcelas(int quantidadeParcelas) {
        this.quantidadeParcelas = quantidadeParcelas;
    }




}


