package br.com.facdombosco.progc.dvo.compras;
// Generated 07/07/2012 11:47:36 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FormaPagamento generated by hbm2java
 */
@Entity
@Table(name="FormaPagamento"
    ,catalog="progc1"
)
public class FormaPagamento  implements java.io.Serializable {


     private Integer idFormaPagamento;
     private String nome;
     private int quantidadeDiasParcela;
     private int quantidadeParcelas;

    public FormaPagamento() {
    }

    public FormaPagamento(String nome, int quantidadeDiasParcela, int quantidadeParcelas) {
       this.nome = nome;
       this.quantidadeDiasParcela = quantidadeDiasParcela;
       this.quantidadeParcelas = quantidadeParcelas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idFormaPagamento", unique=true, nullable=false)
    public Integer getIdFormaPagamento() {
        return this.idFormaPagamento;
    }
    
    public void setIdFormaPagamento(Integer idFormaPagamento) {
        this.idFormaPagamento = idFormaPagamento;
    }
    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="quantidadeDiasParcela", nullable=false)
    public int getQuantidadeDiasParcela() {
        return this.quantidadeDiasParcela;
    }
    
    public void setQuantidadeDiasParcela(int quantidadeDiasParcela) {
        this.quantidadeDiasParcela = quantidadeDiasParcela;
    }
    
    @Column(name="quantidadeParcelas", nullable=false)
    public int getQuantidadeParcelas() {
        return this.quantidadeParcelas;
    }
    
    public void setQuantidadeParcelas(int quantidadeParcelas) {
        this.quantidadeParcelas = quantidadeParcelas;
    }




}


