package br.com.facdombosco.progc.dvo.compras;
// Generated 07/07/2012 11:47:36 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="Fornecedor"
    ,catalog="progc1"
)
public class Fornecedor  implements java.io.Serializable {


     private int idFornecedor;
     private String nome;
     private String cnpj;
     private String telefone;
     private String cidade;
     private String email;

    public Fornecedor() {
    }

	
    public Fornecedor(int idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    public Fornecedor(int idFornecedor, String nome, String cnpj, String telefone, String cidade, String email) {
       this.idFornecedor = idFornecedor;
       this.nome = nome;
       this.cnpj = cnpj;
       this.telefone = telefone;
       this.cidade = cidade;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idFornecedor", unique=true, nullable=false)
    public int getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(int idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    
    @Column(name="nome", length=65535)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="cnpj", length=65535)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    
    @Column(name="telefone", length=65535)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    
    @Column(name="cidade", length=65535)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    
    @Column(name="email", length=65535)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


