package br.com.facdombosco.progc.dvo.compras;
// Generated 30/06/2012 11:42:13 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Requisicao generated by hbm2java
 */
@Entity
@Table(name="Requisicao"
    ,catalog="progc1"
)
public class Requisicao  implements java.io.Serializable {


     private int idRequisicao;
     private Date dataHora;

    public Requisicao() {
    }

    public Requisicao(int idRequisicao, Date dataHora) {
       this.idRequisicao = idRequisicao;
       this.dataHora = dataHora;
    }
   
     @Id 
    
    @Column(name="idRequisicao", unique=true, nullable=false)
    public int getIdRequisicao() {
        return this.idRequisicao;
    }
    
    public void setIdRequisicao(int idRequisicao) {
        this.idRequisicao = idRequisicao;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataHora", nullable=false, length=19)
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }




}


