package br.com.facdombosco.progc.dvo.suprimentos;
// Generated 05/07/2012 22:01:25 by Hibernate Tools 3.2.1.GA


import br.com.facdombosco.progc.dvo.vendas.Produto;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;

/**
 * EstoqueItem generated by hbm2java
 */
@Entity
@Table(name="EstoqueItem"
    ,catalog="progc1"
)
public class EstoqueItem  implements java.io.Serializable {


     private Integer idEstoqueItem;
     private Produto produto;
     private int qtdProduto;

    public EstoqueItem() {
    }

    public EstoqueItem(Produto produto, int qtdProduto) {
       this.produto = produto;
       this.qtdProduto = qtdProduto;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idEstoqueItem", unique=true, nullable=false)
    public Integer getIdEstoqueItem() {
        return this.idEstoqueItem;
    }
    
    public void setIdEstoqueItem(Integer idEstoqueItem) {
        this.idEstoqueItem = idEstoqueItem;
    }
    
    @ManyToOne(fetch= FetchType.EAGER)
    @JoinColumn(name="idProduto")
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    
    @Column(name="qtdProduto", nullable=false)
    public int getQtdProduto() {
        return this.qtdProduto;
    }
    
    public void setQtdProduto(int qtdProduto) {
        this.qtdProduto = qtdProduto;
    }




}


