package br.com.facdombosco.progc.dvo.suprimentos;
// Generated 23/06/2012 10:11:42 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstoqueItem generated by hbm2java
 */
@Entity
@Table(name="EstoqueItem"
    ,catalog="progc1"
)
public class EstoqueItem  implements java.io.Serializable {


     private Integer idEstoqueItem;
     private int idProduto;
     private int qtdProduto;

    public EstoqueItem() {
    }

    public EstoqueItem(int idProduto, int qtdProduto) {
       this.idProduto = idProduto;
       this.qtdProduto = qtdProduto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idEstoqueItem", unique=true, nullable=false)
    public Integer getIdEstoqueItem() {
        return this.idEstoqueItem;
    }
    
    public void setIdEstoqueItem(Integer idEstoqueItem) {
        this.idEstoqueItem = idEstoqueItem;
    }
    
    @Column(name="idProduto", nullable=false)
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    
    @Column(name="qtdProduto", nullable=false)
    public int getQtdProduto() {
        return this.qtdProduto;
    }
    
    public void setQtdProduto(int qtdProduto) {
        this.qtdProduto = qtdProduto;
    }




}


