package br.com.facdombosco.progc.dvo.vendas;
// Generated 16/06/2012 10:52:30 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemVendaId generated by hbm2java
 */
@Embeddable
public class ItemVendaId  implements java.io.Serializable {


     private int idItemVenda;
     private int idVenda;
     private int idProduto;

    public ItemVendaId() {
    }

    public ItemVendaId(int idItemVenda, int idVenda, int idProduto) {
       this.idItemVenda = idItemVenda;
       this.idVenda = idVenda;
       this.idProduto = idProduto;
    }
   

    @Column(name="idItemVenda", nullable=false)
    public int getIdItemVenda() {
        return this.idItemVenda;
    }
    
    public void setIdItemVenda(int idItemVenda) {
        this.idItemVenda = idItemVenda;
    }

    @Column(name="idVenda", nullable=false)
    public int getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(int idVenda) {
        this.idVenda = idVenda;
    }

    @Column(name="idProduto", nullable=false)
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItemVendaId) ) return false;
		 ItemVendaId castOther = ( ItemVendaId ) other; 
         
		 return (this.getIdItemVenda()==castOther.getIdItemVenda())
 && (this.getIdVenda()==castOther.getIdVenda())
 && (this.getIdProduto()==castOther.getIdProduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdItemVenda();
         result = 37 * result + this.getIdVenda();
         result = 37 * result + this.getIdProduto();
         return result;
   }   


}


