package br.com.facdombosco.progc.dvo.vendas;
// Generated 16/06/2012 10:52:30 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemVenda generated by hbm2java
 */
@Entity
@Table(name="ItemVenda"
    ,catalog="progc1"
)
public class ItemVenda  implements java.io.Serializable {


     private ItemVendaId id;
     private Venda venda;
     private Produto produto;
     private String quantidade;

    public ItemVenda() {
    }

	
    public ItemVenda(ItemVendaId id, Venda venda, Produto produto) {
        this.id = id;
        this.venda = venda;
        this.produto = produto;
    }
    public ItemVenda(ItemVendaId id, Venda venda, Produto produto, String quantidade) {
       this.id = id;
       this.venda = venda;
       this.produto = produto;
       this.quantidade = quantidade;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idItemVenda", column=@Column(name="idItemVenda", nullable=false) ), 
        @AttributeOverride(name="idVenda", column=@Column(name="idVenda", nullable=false) ), 
        @AttributeOverride(name="idProduto", column=@Column(name="idProduto", nullable=false) ) } )
    public ItemVendaId getId() {
        return this.id;
    }
    
    public void setId(ItemVendaId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idItemVenda", nullable=false, insertable=false, updatable=false)
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProduto", nullable=false, insertable=false, updatable=false)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    
    @Column(name="quantidade", length=45)
    public String getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(String quantidade) {
        this.quantidade = quantidade;
    }




}


