package br.com.facdombosco.progc.dvo.vendas;
// Generated 05/07/2012 22:15:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name="Vendedor"
    ,catalog="progc1"
)
public class Vendedor  implements java.io.Serializable {


     private Integer idVendedor;
     private String nome;
     private Set vendas = new HashSet(0);

    public Vendedor() {
    }

    public Vendedor(String nome, Set vendas) {
       this.nome = nome;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idVendedor", unique=true, nullable=false)
    public Integer getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(Integer idVendedor) {
        this.idVendedor = idVendedor;
    }
    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="vendedor", targetEntity=Venda.class)
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


