package br.com.facdombosco.progc.dvo.vendas;
// Generated 16/06/2012 10:52:30 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="PESSOA"
    ,catalog="progc1"
)
public class Pessoa  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Integer idade;

    public Pessoa() {
    }

    public Pessoa(String nome, Integer idade) {
       this.nome = nome;
       this.idade = idade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nome", length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="idade")
    public Integer getIdade() {
        return this.idade;
    }
    
    public void setIdade(Integer idade) {
        this.idade = idade;
    }




}


